language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=announcementcenter
  matrix:
    - DB=mysql

branches:
  only:
    - master
    - /^stable\d*$/

matrix:
  include:
    - php: 5.5
      env: DB=sqlite
    - php: 5.5
      env: DB=postgresql
  allow_failures:
    - php: hhvm
  fast_finish: true

install:
  # install ocdev
  - sudo apt-get -y install python3-jinja2 python3-setuptools
  - sudo easy_install3 requests
  - sudo easy_install3 ocdev

  # set up postgresql
  - sh -c "if [ '$DB' = 'postgresql' ]; then createuser -U travis -s oc_autotest; fi"

  # set up mysql
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database oc_autotest;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -e \"CREATE USER 'oc_autotest'@'localhost';\"; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -e \"grant all on oc_autotest.* to 'oc_autotest'@'localhost';\"; fi"

  # install owncloud
  - cd ..
  - ocdev setup core --dir owncloud --branch $CORE_BRANCH --no-history
  - cd owncloud
  - ocdev ci $DB

  # enable announcementcenter
  - mv ../$APP_NAME apps/
  - php -f console.php app:enable $APP_NAME

before_script:
  - cd apps/$APP_NAME

script:
  - phpunit -c phpunit.xml
  - phpunit -c phpunit.integration.xml
